development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: first_app_dev
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: first_app_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  template: template0
